name: better_share_handler
description: Handle text, images, videos and files shared to your Flutter app from other apps on iOS and Android, and add share suggestions/shortcuts.
version: 1.1.0
repository: https://github.com/sampaioxsamuel/better_share_handler
issue_tracker: https://github.com/sampaioxsamuel/better_share_handler/issues
topics:
  - share
  - share-extension
  - intent
  - deep-linking

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.sampaioxsamuel.better_share_handler
        pluginClass: BetterShareHandlerPlugin
      ios:
        pluginClass: BetterShareHandlerPlugin
